name: network_service
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dio: ^5.3.3
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  talker_dio_logger: ^1.0.2

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  very_good_analysis: ^3.1.0
