name: currency_data_api
description: Dart package which manages the meta data domain.
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.7.0
  network_service:
    path: ../network_service

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0