name: data_repository
description: Dart package which manages the meta data domain.
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  currency_data_api:
    path: ../currency_data_api
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  gold_data_api:
    path: ../gold_data_api



dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0